name: ForkSync
run-name: Syncing the fork
on:
  schedule:
    - cron:  '2 20 * * 4'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge upstream
        run: |
          echo "Pull repo...";
          git pull --unshallow;
          echo "Pulled. Configure bot...";
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com";
          git config --global user.name "github-actions[bot]";
          echo ${{ github.token }} | gh auth login --with-token;
          UPSTREAM=$(gh api repos/:owner/:repo --jq .parent.full_name);
          if [ -z $UPSTREAM ]; then
            echo "Can't find upstream" >&2 && exit 1;
          fi;
          if [ ! $(echo $UPSTREAM | egrep '^(http|git@)') ]; then
            UPSTREAM=https://github.com/$UPSTREAM.git
          fi;
          echo $UPSTREAM;
          git remote add upstream $UPSTREAM;
          echo "Fetch upstream...";
          git fetch upstream master;
          echo "Fetched. Rebase differences...";
          fork_point=$(git merge-base upstream/master origin/core);
          echo $fork_point;
          git rebase --onto upstream/master $fork_point origin/core;
          echo "Rebased. Push to origin...";
          git push --force-with-lease origin HEAD:core;
